amendments:
  fields:
  - amendment_id
  - amended_bill_id
  - amended_amendment_id
  - amended_treaty_id
  - chamber
  - amendment_type
  - amendment_number
  - congress
  - purpose
  - description
  - submitted_at
  - proposed_at
  - notes
  - cosponsors_count
  - actions_count
  - amendments_to_amendment_count
  - updated_at
  id_fields:
  - amendment_id
  main: true
  nested_fields: {}
  related_fields:
  - actions
  - cosponsors
  - texts
amendments_actions:
  fields:
  - amendment_id
  - action_id
  - action_code
  - action_date
  - text
  - action_type
  - source_system
  - source_system_code
  - calendar
  - calendar_number
  id_fields:
  - action_id
  main: false
  nested_fields: {}
  related_fields: []
amendments_cosponsors:
  fields:
  - amendment_id
  - bioguide_id
  id_fields: []
  main: false
  nested_fields: {}
  related_fields: []
amendments_texts:
  fields:
  - amendment_id
  - description
  - date
  - type
  - formatted_text
  - pdf
  - html
  - xml
  - url
  id_fields: []
  main: false
  nested_fields: {}
  related_fields: []
bills:
  fields:
  - bill_id
  - bill_type
  - bill_number
  - congress
  - title
  - origin_chamber
  - origin_chamber_code
  - introduced_at
  - constitutional_authority_statement_text
  - is_law
  - notes
  - policy_area
  - actions_count
  - amendments_count
  - committees_count
  - cosponsors_count
  - bill_relations_count
  - summaries_count
  - subjects_count
  - titles_count
  - texts_count
  - updated_at
  id_fields:
  - bill_id
  main: true
  nested_fields: {}
  related_fields:
  - actions
  - cosponsors
  - billrelations
  - texts
  - titles
  - summaries
  - subjects
bills_actions:
  fields:
  - bill_id
  - action_id
  - action_code
  - action_date
  - text
  - action_type
  - source_system
  - source_system_code
  - calendar
  - calendar_number
  id_fields:
  - bill_id
  - action_id
  main: false
  nested_fields: {}
  related_fields: []
bills_billrelations:
  fields:
  - bill_id
  - relatedbill_id
  - relationship_identified_by_1
  - relationship_type_1
  - relationship_identified_by_2
  - relationship_type_2
  - relationship_identified_by_3
  - relationship_type_3
  id_fields: []
  main: false
  nested_fields: {}
  related_fields: []
bills_cosponsors:
  fields:
  - bill_id
  - bioguide_id
  id_fields: []
  main: false
  nested_fields: {}
  related_fields: []
bills_subjects:
  fields:
  - bill_id
  - subject
  - updated_at
  id_fields: []
  main: false
  nested_fields: {}
  related_fields: []
bills_summaries:
  fields:
  - bill_id
  - action_date
  - action_desc
  - text
  - version_code
  - updated_at
  id_fields: []
  main: false
  nested_fields: {}
  related_fields: []
bills_texts:
  fields:
  - bill_id
  - description
  - date
  - type
  - formatted_text
  - pdf
  - html
  - xml
  - url
  id_fields: []
  main: false
  nested_fields: {}
  related_fields: []
bills_titles:
  fields:
  - bill_id
  - title
  - title_type
  - bill_text_version_code
  - bill_text_version_name
  - chamber_code
  - chamber_name
  - title_type_code
  id_fields: []
  main: false
  nested_fields: {}
  related_fields: []
committeemeetings:
  fields:
  - meeting_id
  - chamber
  - congress
  - title
  - date
  - meeting_type
  - meeting_status
  - room
  - building
  - address
  - updated_at
  id_fields:
  - meeting_id
  main: true
  nested_fields: {}
  related_fields:
  - committees
  - meetingdocuments
  - bills
  - treaties
  - nominations
  - hearings
committeemeetings_bills:
  fields:
  - meeting_id
  - bill_id
  id_fields: []
  main: false
  nested_fields: {}
  related_fields: []
committeemeetings_committees:
  fields:
  - meeting_id
  - committee
  - committee_code
  - chamber
  id_fields: []
  main: false
  nested_fields: {}
  related_fields: []
committeemeetings_hearings:
  fields:
  - meeting_id
  - hearing_id
  id_fields: []
  main: false
  nested_fields: {}
  related_fields: []
committeemeetings_meetingdocuments:
  fields:
  - meeting_id
  - description
  - date
  - type
  - formatted_text
  - pdf
  - html
  - xml
  - url
  id_fields: []
  main: false
  nested_fields: {}
  related_fields: []
committeemeetings_nominations:
  fields:
  - meeting_id
  - nomination_id
  id_fields: []
  main: false
  nested_fields: {}
  related_fields: []
committeemeetings_treaties:
  fields:
  - meeting_id
  - treaty_id
  id_fields: []
  main: false
  nested_fields: {}
  related_fields: []
committeeprints:
  fields:
  - print_id
  - print_jacketnumber
  - title
  - chamber
  - congress
  - print_number
  - citation
  - texts_count
  - updated_at
  id_fields:
  - print_id
  main: true
  nested_fields: {}
  related_fields:
  - texts
committeeprints_texts:
  fields:
  - print_id
  - type
  - formatted_text
  - pdf
  - html
  - xml
  - url
  id_fields: []
  main: false
  nested_fields: {}
  related_fields: []
committeereports:
  fields:
  - report_id
  - citation
  - report_type
  - report_number
  - report_part
  - congress
  - session_number
  - chamber
  - title
  - issued_at
  - is_conference_report
  - texts_count
  - updated_at
  id_fields:
  - report_id
  main: true
  nested_fields: {}
  related_fields:
  - texts
committeereports_texts:
  fields:
  - report_id
  - formatted_text
  - pdf
  - formatted_text_is_errata
  - pdf_is_errata
  id_fields: []
  main: false
  nested_fields: {}
  related_fields: []
committees:
  fields:
  - committee_code
  - committee_type
  - chamber
  - name
  - is_subcommittee
  - is_current
  - bills_count
  - reports_count
  - nominations_count
  - updated_at
  id_fields:
  - committee_code
  main: true
  nested_fields: {}
  related_fields:
  - bills
  - associated_reports
committees_associated_reports:
  fields:
  - committee_code
  - report_id
  id_fields: []
  main: false
  nested_fields: {}
  related_fields: []
committees_bills:
  fields:
  - committee_code
  - bill_id
  - relationship_type
  - committee_action_date
  - updated_at
  id_fields:
  - committee_code
  - bill_id
  main: false
  nested_fields: {}
  related_fields: []
committees_subcommittees:
  fields:
  - parent_committee_code
  - committee_code
  - is_current
  - bills_count
  - updated_at
  id_fields:
  - parent_committee_code
  - committee_code
  main: false
  nested_fields: {}
  related_fields:
  - relatedreports
  - bills
congresses:
  fields:
  - number
  - name
  - start_year
  - end_year
  - updated_at
  id_fields:
  - name
  main: true
  nested_fields: {}
  related_fields: []
hearings:
  fields:
  - hearing_id
  - jacketnumber
  - loc_id
  - title
  - citation
  - chamber
  - congress
  - hearing_number
  - part_number
  - updated_at
  id_fields:
  - hearing_id
  main: true
  nested_fields: {}
  related_fields:
  - committees
  - texts
  - associatedmeetings
hearings_associatedmeetings:
  fields:
  - hearing_id
  - meeting_id
  - title
  - date
  - chamber
  id_fields: []
  main: false
  nested_fields: {}
  related_fields: []
hearings_committees:
  fields:
  - hearing_id
  - committee
  - committee_code
  - chamber
  id_fields: []
  main: false
  nested_fields: {}
  related_fields: []
hearings_texts:
  fields:
  - hearing_id
  - description
  - date
  - type
  - formatted_text
  - pdf
  - html
  - xml
  - url
  id_fields: []
  main: false
  nested_fields: {}
  related_fields: []
members:
  fields:
  - bioguide_id
  - direct_order_name
  - inverted_order_name
  - honorific_name
  - first_name
  - middle_name
  - last_name
  - suffix_name
  - nickname
  - party
  - state
  - district
  - birth_year
  - death_year
  - official_url
  - office_address
  - office_city
  - office_district
  - office_zip
  - office_phone_number
  - sponsored_legislation_count
  - cosponsored_legislation_count
  - depiction_image_url
  - depiction_attribution
  - is_current_member
  - updated_at
  id_fields:
  - bioguide_id
  main: true
  nested_fields: {}
  related_fields: []
nominations:
  fields:
  - nomination_id
  - citation
  - congress
  - nomination_number
  - part_number
  - description
  - received_at
  - authority_date
  - is_privileged
  - is_civilian
  - executive_calendar_number
  - committees_count
  - actions_count
  - hearings_count
  - updated_at
  id_fields:
  - nomination_id
  main: true
  nested_fields: {}
  related_fields:
  - actions
  - committeeactivities
  - nominees
  - hearings
nominations_actions:
  fields:
  - nomination_id
  - action_id
  - action_code
  - action_date
  - text
  - action_type
  id_fields:
  - nomination_id
  - action_id
  main: false
  nested_fields: {}
  related_fields: []
nominations_committeeactivities:
  fields:
  - nomination_id
  - activity_date
  - activity_name
  - committee
  - committee_code
  - subcommittee_activity_date
  - subcommittee_activity_name
  - subcommittee_name
  - subcommittee_code
  id_fields: []
  main: false
  nested_fields: {}
  related_fields: []
nominations_hearings:
  fields:
  - nomination_id
  - hearing_id
  - part_number
  - errata_number
  id_fields: []
  main: false
  nested_fields: {}
  related_fields: []
nominations_nomineepositions:
  fields:
  - nomination_id
  - ordinal
  - intro_text
  - position_title
  - organization
  - nominee_count
  id_fields: []
  main: false
  nested_fields: {}
  related_fields: []
nominations_nominees:
  fields:
  - nomination_id
  - ordinal
  - first_name
  - last_name
  - middle_name
  - prefix
  - suffix
  - state
  - effective_date
  - predecessor_name
  - corps_code
  id_fields: []
  main: false
  nested_fields: {}
  related_fields: []
treaties:
  fields:
  - treaty_id
  - number
  - suffix
  - congress_received
  - congress_considered
  - topic
  - in_force_at
  - transmitted_at
  - resolution_text
  - parts_count
  - actions_count
  - old_number
  - old_number_display_name
  - updated_at
  id_fields:
  - treaty_id
  main: true
  nested_fields: {}
  related_fields:
  - actions
treaties_actions:
  fields:
  - treaty_id
  - action_code
  - action_id
  - action_date
  - text
  - action_type
  id_fields:
  - treaty_id
  - action_id
  main: false
  nested_fields: {}
  related_fields: []
