- name: nominations
  description: Congressional nominations main data

  api:
    list_key: nominations
    full_key: nomination
    api_endpoint: nomination
    page_size: 250
    retry_attempts: 3

  schema:
    table_name: nominations
    is_main: true
    create_raw: true
    id_fields: [nomination_id]
    related_tables:
      - actions
      # - positions
      - committeeactivities
      - hearings
      - individualnominees

  processing:
    batch_size: 100
    checkpoint_frequency: 50

- name: nominations_actions
  description: Nomination actions data

  api:
    expected_key: actions
    outer_field: actions
    page_size: 250
    retry_attempts: 3

  schema:
    table_name: nominations_actions
    is_main: false
    create_raw: true
    id_fields: [action_id, nomination_id]
    related_tables:
      - committees

  processing:
    batch_size: 500
    checkpoint_frequency: 250

- name: nominations_actions_committees
  description: Nomination actions committees data

  schema:
    table_name: nominations_actions_committees
    is_main: false
    create_raw: false
    id_fields: [action_id, nomination_id, committee_code]

  processing:
    batch_size: 500
    checkpoint_frequency: 250


- name: nominations_nominees
  description: Nomination positions data - will be routed into nominations_positions

  schema:
    table_name: nominations_nominees
    is_main: false
    create_raw: false
    id_fields: [nomination_id, position_id]
    related_tables:
      # - individualnominees

  processing:
    batch_size: 500
    checkpoint_frequency: 250

- name: nominations_individualnominees
  description: Nomination nominees data - will be routed into nominations_nominees

  api:
    list_key: nominees
    api_endpoint: nominees
    page_size: 250
    retry_attempts: 3

  schema:
    table_name: nominations_individualnominees
    is_main: false
    create_raw: true
    id_fields: [nomination_id, position_id, nominee_ordinal]

  processing:
    batch_size: 500
    checkpoint_frequency: 250

- name: nominations_hearings
  description: Nomination hearings data

  schema:
    table_name: nominations_hearings
    is_main: false
    create_raw: true
    id_fields: [nomination_id, hearing_id]

  processing:
    batch_size: 500
    checkpoint_frequency: 250

- name: nominations_committeeactivities
  description: Nomination committee activities data

  api:
    list_key: committees
    api_endpoint: committees
    page_size: 250
    retry_attempts: 3

  schema:
    table_name: nominations_committeeactivities
    is_main: false
    create_raw: true
    id_fields: [nomination_id, committee_code]

  processing:
    batch_size: 500
    checkpoint_frequency: 250
